package cmd

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/Grey-Magic/kunji/pkg/validators"
	"github.com/pterm/pterm"
	"github.com/spf13/cobra"
)

var generateDocsCmd = &cobra.Command{
	Use:    "generate-docs",
	Short:  "Generate PROVIDERS.md",
	Hidden: true,
	Run: func(cmd *cobra.Command, args []string) {
		providers, err := validators.GetAllProviders()
		if err != nil {
			pterm.Error.Printfln("Error loading providers: %v", err)
			return
		}

		sort.Slice(providers, func(i, j int) bool {
			if providers[i].Category == providers[j].Category {
				return providers[i].Name < providers[j].Name
			}
			return providers[i].Category < providers[j].Category
		})

		var sb strings.Builder
		sb.WriteString("# Supported Providers\n\n")
		sb.WriteString("This file is auto-generated by running `kunji generate-docs`.\n\n")
		sb.WriteString(fmt.Sprintf("Currently supporting **%d** providers.\n\n", len(providers)))
		sb.WriteString("| Provider | Category | Prefixes |\n")
		sb.WriteString("|---|---|---|\n")

		for _, p := range providers {
			prefixes := "-"
			if len(p.KeyPrefixes) > 0 {
				escaped := make([]string, len(p.KeyPrefixes))
				for i, px := range p.KeyPrefixes {
					escaped[i] = "`" + px + "`"
				}
				prefixes = strings.Join(escaped, ", ")
			}
			sb.WriteString(fmt.Sprintf("| %s | %s | %s |\n", p.Name, p.Category, prefixes))
		}

		err = os.WriteFile("PROVIDERS.md", []byte(sb.String()), 0644)
		if err != nil {
			pterm.Error.Printfln("Failed to write PROVIDERS.md: %v", err)
			return
		}

		pterm.Success.Println("Generated PROVIDERS.md")
	},
}

func init() {
	rootCmd.AddCommand(generateDocsCmd)
}
